steps:
  - id: git-submodule
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    env: ['GIT_DISCOVERY_ACROSS_FILESYSTEM=1']
    args:
    - '-c'
    - |
      git init
      git config -f .gitmodules submodule.common.url https://github.com/thzero/societySidekick_common.git
      git submodule init
      git submodule update
